apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
spec:
  type: NodePort
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # You can change this if needed
